export const ACTION_TYPE = 'ACTION_TYPE';
export const AUTHENTICATION_TYPE = 'AUTHENTICATION_TYPE';
export const SOCIAL_AUTH_ACTION = 'SOCIAL_AUTH_ACTION';
export const CHANGE_TOGGLE = 'CHANGE_TOGGLE';
export const CHANGE_OS_DESIGN = 'CHANGE_OS_DESIGN';
export const LOADING_ACTION = "LOADING_ACTION";
